language: go
sudo: false
matrix:
  include:
  - go: tip
  allow_failures:
  - go: tip
script:
- ".travis/build-all"
- go get golang.org/x/tools/cmd/cover
- go test -coverprofile fmt
deploy:
  provider: releases
  api_key:
    secure: IiP16ghRGSD6lk+dEtMlqlyvFWY9DOwXrOFWdEBs6jqkdAD4dFzBsVXtBC+PNfJ4UxP7gosrdmRSEWYewNg8h3VoUVssb+YEpz8O/539TavvStEM7eHm+WiFQXgaHCs2fKOxmN+/I6s9Gkb7J0/WdcJOJbXpstw3o0dm4WjiYglkivGD6Hkt9y8OpEJIbLmn6TZpG9/80stfoUEbW+5FidaGS8tCpwhAYUFD7EcNnAMZRYKQeAERe+vOK/8c3m0UhKcWe+cWDapepE+bqSLfzFrsGYsccGv6f8k0AeMBkrP1Yat6Bnp1EdOpOb/XxkkHoEvKz/wLxwNvwOkRuQoh3IMkzc8odQTAxl2I0eDB0FIi0vUwZLU0beMTF64Zas2qfw3Uml7wSShhOqRwCrtN+L/2BnX+ZhI46qAOCGWDuksr6CnYwF2MJDPYHPtPy2W+rf2BkeUj6EKvT1OHso3NiM9y1M4pVRTz5y452WuqdFdkFA4oly2yRFB9Yz1ZSCD91WlH/zlfDSKo9SBwaq6a0WkUQ5kFafLNBi+cXFfvx0hmN4XstVHZiFpDFhgKRoWtRMfzZW0jzAhnPMsLIkX82H567imFH79K/NjRmnHspYX9gNUlqWdrDnUbL3qZ9uXKKao50ENjq2LPSNW6QxjgZn+PeyoN6yyUv4agknXpjho=
  file_glob: true
  file:
    - overseer-*
    - *-bridge-*
  skip_cleanup: true
  on:
    tags: true
