apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: overseer
  name: overseer-k8s-event-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overseer-k8s-event-watcher
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: overseer-k8s-event-watcher
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: overseer-k8s-event-watcher
subjects:
- kind: ServiceAccount
  name: overseer-k8s-event-watcher
  namespace: overseer