apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: overseer
  name: overseer-worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overseer-worker
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: overseer-worker
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: overseer-worker
subjects:
  - kind: ServiceAccount
    name: overseer-worker
    namespace: overseer