apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: overseer
  labels:
    app: redis
spec:
  serviceName: redis-headless
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.5-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h localhost ping"
---
apiVersion: v1
kind: Service
metadata:
  namespace: overseer
  name: redis-headless
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  namespace: overseer
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379