on: push
name: Push Event
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        # No alpine, lacking cgo support
        uses: docker://golang:1.13.1
        with:
          entrypoint: sh
          args: .github/run-tests.sh