on:
  release:
    types: [published]
name: Handle release
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload binaries
        uses: docker://golang:1.13.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: bash
          args: .github/upload-script.sh