on:
  release:
    types: [published]
name: Handle release
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Store current git tag
      - run: |
          git describe --tags 2>/dev/null > DOCKER_BUILD_VERSION
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker base
        run: bash scripts/docker-build-hub.sh overseer Dockerfile
      - name: Build docker webhook bridge
        run: bash scripts/docker-build-hub.sh overseer-webhook-bridge Dockerfile.webhook-bridge
      - name: Build docker email bridge
        run: bash scripts/docker-build-hub.sh overseer-email-bridge Dockerfile.email-bridge
      - name: Build docker queue bridge
        run: bash scripts/docker-build-hub.sh overseer-queue-bridge Dockerfile.queue-bridge
      - name: Upload binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bin/*-*'