on: release
name: Handle Release
jobs:
  upload-to-docker-hub:
    name: Upload to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build base
        uses: actions/docker/cli@master
        with:
          entrypoint: bash
          args: scripts/docker-build-hub.sh overseer
      - name: Build webhook bridge
        uses: actions/docker/cli@master
        with:
          entrypoint: bash
          args: scripts/docker-build-hub.sh overseer-webhook-bridge Dockerfile.webhook-bridge
  upload-to-github:
    name: Upload to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*-*'