on: release
name: Handle Release
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker base
        uses: actions/docker/cli@master
        with:
          entrypoint: sh
          args: scripts/docker-build-hub.sh overseer scripts/Dockerfile
      - name: Build docker webhook bridge
        uses: actions/docker/cli@master
        with:
          entrypoint: sh
          args: scripts/docker-build-hub.sh overseer-webhook-bridge scripts/Dockerfile.webhook-bridge
      - name: Upload binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bin/*-*'